const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  _id: { type: mongoose.Schema.Types.ObjectId, auto: true }, // Auto-generated by MongoDB
  username: { type: String, unique: true, required: true }, // Unique display name
  email: { type: String, unique: true, required: true },    // Unique, for login
  password: { type: String, required: true },               // Hashed with bcrypt
  avatarUrl: { type: String },                              // Profile picture (optional, Cloudinary URL)
  bio: { type: String },                                    // Short description (optional)
  joinDate: { type: Date, default: Date.now },              // Registration timestamp
  lastPostedAt: { type: Date },                             // Track streak

});

module.exports = mongoose.model('User', UserSchema);
export default UserSchema;